//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string Id { get; set; }
        public string DepartmentName { get; set; }
        public string IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
