//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_
    {
        public string EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeCNName { get; set; }
        public string EmployeeVNName { get; set; }
        public string EmployeeAvatar { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Email { get; set; }
        public string DeskPhone { get; set; }
        public string MobilePhone { get; set; }
        public string DepartmentByAPI { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsBoss { get; set; }
        public Nullable<int> Position { get; set; }
    }
}
