//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSC()
        {
            this.Signs = new HashSet<SignMSC>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string IdUserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Subject { get; set; }
        public string Process { get; set; }
        public string Model { get; set; }
        public string BeforeChange { get; set; }
        public string BeforeChangeFile { get; set; }
        public string AfterChange { get; set; }
        public string AfterChangeFile { get; set; }
        public string Reason { get; set; }
        public string CalcCost { get; set; }
        public Nullable<int> Status { get; set; }
        public string IdCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignMSC> Signs { get; set; }
        public User UserCreated { get; set; }
        public Customer Customer { get; set; }
    }
}
