//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCN_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCN_()
        {
            this.PCNConfirms = new HashSet<PCNConfirm_>();
        }
    
        public string PCNID { get; set; }
        public string PCNCode { get; set; }
        public string RecommendedBy { get; set; }
        public Nullable<System.DateTime> RecommendedDate { get; set; }
        public string Subject { get; set; }
        public string ProcessTitle { get; set; }
        public string BeforeChangeDescription { get; set; }
        public string BeforeChangeFile { get; set; }
        public string ModelTitle { get; set; }
        public string AfterChangeDescription { get; set; }
        public string AfterChangeFile { get; set; }
        public string Reason { get; set; }
        public string CalculateCost { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string IEConfirmBy { get; set; }
        public Nullable<System.DateTime> IEConfirmDate { get; set; }
        public string BossConfirmBy { get; set; }
        public Nullable<System.DateTime> BossConfirmDate { get; set; }
        public string IERejectBy { get; set; }
        public Nullable<System.DateTime> IERejectDate { get; set; }
        public string RejectReason { get; set; }
        public string BossRejectBy { get; set; }
        public Nullable<System.DateTime> BossRejectDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCNConfirm_> PCNConfirms { get; set; }
    }
}
