//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcnEntities : DbContext
    {
        public PcnEntities()
            : base("name=PcnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_> Customer_Set { get; set; }
        public virtual DbSet<DepartmentEmployee_> DepartmentEmployee_Set { get; set; }
        public virtual DbSet<Department_> Department_Set { get; set; }
        public virtual DbSet<Employee_> Employee_Set { get; set; }
        public virtual DbSet<PCNConfirm_> PCNConfirm_Set { get; set; }
        public virtual DbSet<PCN_> PCN_Set { get; set; }
    }
}
