//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_MSC.Areas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        public string IdUser { get; set; }
        public string IdApplication { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public string Detail { get; set; }
        public string IdCustomer { get; set; }
        public string IdDepartment { get; set; }
    
        public virtual User User { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
    }
}
